-- =========================
-- Accounts
-- =========================

CREATE TABLE banks (
                       id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name        varchar NOT NULL,
                       created_at  timestamptz NOT NULL DEFAULT now(),
                       created_by  varchar,
                       updated_at  timestamptz,
                       updated_by  varchar,
                       deleted_at  timestamptz,
                       deleted_by  varchar
);

CREATE TABLE accounts (
                          id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          bank_id        integer NOT NULL REFERENCES banks(id),
                          account_type   char(3),
                          name           varchar NOT NULL,
                          owner          varchar,
                          currency_type  char(3) NOT NULL,
                          account_number varchar,
                          description    varchar,
                          created_at     timestamptz NOT NULL DEFAULT now(),
                          created_by     varchar,
                          updated_at     timestamptz,
                          updated_by     varchar,
                          deleted_at     timestamptz,
                          deleted_by     varchar
);

-- =========================
-- Ministries
-- =========================

CREATE TABLE ministries (
                            id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            name        varchar NOT NULL,
                            description varchar,
                            created_at  timestamptz NOT NULL DEFAULT now(),
                            created_by  varchar,
                            updated_at  timestamptz,
                            updated_by  varchar,
                            deleted_at  timestamptz,
                            deleted_by  varchar
);

CREATE TABLE account_ministries (
                                    id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                    account_id  integer NOT NULL REFERENCES accounts(id),
                                    ministry_id integer NOT NULL REFERENCES ministries(id),
                                    created_at  timestamptz NOT NULL DEFAULT now(),
                                    created_by  varchar,
                                    updated_at  timestamptz,
                                    updated_by  varchar,
                                    deleted_at  timestamptz,
                                    deleted_by  varchar
);

-- =========================
-- Entries
-- =========================

CREATE TABLE tags (
                      id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name        varchar NOT NULL,
                      created_at  timestamptz NOT NULL DEFAULT now(),
                      created_by  varchar,
                      updated_at  timestamptz,
                      updated_by  varchar,
                      deleted_at  timestamptz,
                      deleted_by  varchar
);

CREATE TABLE sources (
                         id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name        varchar NOT NULL,
                         description varchar,
                         created_at  timestamptz NOT NULL DEFAULT now(),
                         created_by  varchar,
                         updated_at  timestamptz,
                         updated_by  varchar,
                         deleted_at  timestamptz,
                         deleted_by  varchar
);

CREATE TABLE entries (
                         id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         account_id  integer NOT NULL REFERENCES accounts(id),
                         date        timestamptz NOT NULL,
                         amount      numeric NOT NULL DEFAULT 0,
                         memo        varchar,
                         created_at  timestamptz NOT NULL DEFAULT now(),
                         created_by  varchar,
                         updated_at  timestamptz,
                         updated_by  varchar,
                         deleted_at  timestamptz,
                         deleted_by  varchar
);

CREATE TABLE expenses (
                          entry_id    integer PRIMARY KEY REFERENCES entries(id),
                          merchant    varchar NOT NULL,
                          ministry_id integer NOT NULL REFERENCES ministries(id),
                          tag_id      integer REFERENCES tags(id),
                          created_at  timestamptz NOT NULL DEFAULT now(),
                          created_by  varchar,
                          updated_at  timestamptz,
                          updated_by  varchar,
                          deleted_at  timestamptz,
                          deleted_by  varchar
);

CREATE TABLE incomes (
                         entry_id    integer PRIMARY KEY REFERENCES entries(id),
                         source_id   integer NOT NULL REFERENCES sources(id),
                         created_at  timestamptz NOT NULL DEFAULT now(),
                         created_by  varchar,
                         updated_at  timestamptz,
                         updated_by  varchar,
                         deleted_at  timestamptz,
                         deleted_by  varchar
);

CREATE TABLE thesauruses (
                             account_id  integer NOT NULL,
                             merchant    varchar NOT NULL,
                             ministry_id integer NOT NULL,
                             tag_id      integer NULL,
                             created_at  timestamp NOT NULL DEFAULT now(),
                             created_by  varchar NULL,
                             updated_at  timestamp NULL DEFAULT NULL,
                             updated_by  varchar NULL DEFAULT NULL,
                             deleted_at  timestamp NULL DEFAULT NULL,
                             deleted_by  varchar NULL DEFAULT NULL
);

-- =========================
-- Budget
-- =========================

CREATE TABLE budget (
                        id           integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        ministry_id  integer NOT NULL REFERENCES ministries(id),
                        income_id    integer REFERENCES incomes(entry_id),
                        date         timestamptz,
                        budget_type  char(3) NOT NULL,
                        amount       numeric NOT NULL DEFAULT 0,
                        memo         varchar,
                        created_at   timestamptz NOT NULL DEFAULT now(),
                        created_by   varchar,
                        updated_at   timestamptz,
                        updated_by   varchar,
                        deleted_at   timestamptz,
                        deleted_by   varchar
);

CREATE TABLE contributions (
                               id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               budget_id   integer NOT NULL REFERENCES budget(id),
                               expense_id  integer NOT NULL REFERENCES expenses(entry_id),
                               date        timestamptz,
                               memo        varchar,
                               created_at  timestamptz NOT NULL DEFAULT now(),
                               created_by  varchar,
                               updated_at  timestamptz,
                               updated_by  varchar,
                               deleted_at  timestamptz,
                               deleted_by  varchar
);

-- =========================
-- Fixed
-- =========================

CREATE TABLE fixed (
                       id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       account_id  integer NOT NULL REFERENCES accounts(id),
                       ministry_id integer NOT NULL REFERENCES ministries(id),
                       name        varchar NOT NULL,
                       fixed_day   integer,
                       description varchar,
                       created_at  timestamptz NOT NULL DEFAULT now(),
                       created_by  varchar,
                       updated_at  timestamptz,
                       updated_by  varchar,
                       deleted_at  timestamptz,
                       deleted_by  varchar
);

CREATE TABLE fixed_expenses (
                                id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                fixed_id    integer NOT NULL REFERENCES fixed(id),
                                expense_id  integer REFERENCES expenses(entry_id),
                                memo        varchar,
                                created_at  timestamptz NOT NULL DEFAULT now(),
                                created_by  varchar,
                                updated_at  timestamptz,
                                updated_by  varchar,
                                deleted_at  timestamptz,
                                deleted_by  varchar
);

-- =========================
-- System
-- =========================

CREATE TABLE types (
                       id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       name        varchar NOT NULL,
                       description varchar,
                       created_at  timestamptz NOT NULL DEFAULT now(),
                       created_by  varchar,
                       updated_at  timestamptz,
                       updated_by  varchar,
                       deleted_at  timestamptz,
                       deleted_by  varchar
);

CREATE TABLE codes (
                       id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       type_id     integer NOT NULL REFERENCES types(id),
                       code        varchar NOT NULL,
                       name        varchar NOT NULL,
                       description varchar,
                       created_at  timestamptz NOT NULL DEFAULT now(),
                       created_by  varchar,
                       updated_at  timestamptz,
                       updated_by  varchar,
                       deleted_at  timestamptz,
                       deleted_by  varchar,
                       UNIQUE (type_id, code)
);

CREATE TABLE configs (
                         id          integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name        varchar NOT NULL,
                         value       varchar NOT NULL,
                         created_at  timestamp NOT NULL DEFAULT now(),
                         created_by  varchar NULL,
                         updated_at  timestamp NULL DEFAULT NULL,
                         updated_by  varchar NULL DEFAULT NULL,
                         deleted_at  timestamp NULL DEFAULT NULL,
                         deleted_by  varchar NULL DEFAULT NULL
);

-- =========================
-- View
-- =========================

create or replace view v_accounts as
select
    acc.id
     , acc.bank_id
     , bnk.name as "bank_name"
     , acc.account_type
     , acc.name
     , acc.owner
     , acc.currency_type
     , acc.account_number
     , acc.description
     , acc.created_at
     , acc.created_by
     , acc.updated_at
     , acc.updated_by
from
    accounts acc
        left join
    banks bnk
    on acc.bank_id = bnk.id
where
    acc.deleted_at is null
;

create or replace view v_incomes as
select
    ent.id
     , ent.account_id
     , ent.date
     , ent.amount
     , inc.source_id
     , src.name as "source_name"
     , ent.created_at
     , ent.created_by
     , ent.updated_at
     , ent.updated_by
from
    entries ent
        join
    incomes inc
    on ent.id = inc.entry_id
        left join
    sources src
    on inc.source_id = src.id
where
    ent.deleted_at is null
;

create or replace view v_expenses as
select
    ent.id
     , ent.account_id
     , ent.date
     , ent.amount
     , epn.merchant
     , epn.tag_id
     , tgs.name as "tag"
     , epn.ministry_id
     , mst.name as "ministry_name"
     , fe.fixed_id
     , fxd.name as "fixed_name"
     , ent.created_at
     , ent.created_by
     , ent.updated_at
     , ent.updated_by
from
    entries ent
        join
    expenses epn
    on ent.id = epn.entry_id
        left join
    tags tgs
    on epn.tag_id = tgs.id
        left join
    ministries mst
    on epn.ministry_id = mst.id
        left join
    fixed_expenses fe
    on epn.entry_id = fe.expense_id
        left join
    fixed fxd
    on fe.fixed_id = fxd.id
where
    ent.deleted_at is null
;



