create table users(
    id      integer generated by default as identity primary key,
    user_id varchar unique,
    credential_id varchar,
    public_key varchar,
    signature_count integer,
    created_at   timestamptz NOT NULL DEFAULT now(),
    created_by   varchar,
    updated_at   timestamptz,
    updated_by   varchar,
    deleted_at   timestamptz,
    deleted_by   varchar
);

