/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  InvalidateOptions,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AccountUpdateRequest,
  ApiResponseListAccountResponse,
  ApiResponseListBankResponse,
  ApiResponseListCodeResponse,
  ApiResponseListMinistryResponse,
  ApiResponseListTypeResponse,
  ApiResponseLoginResponse,
  ApiResponseStartRegistrationResponse,
  ApiResponseTokenResponse,
  ApiResponseVoid,
  BankUpdateRequest,
  CodeUpdateRequest,
  EntryInputRequest,
  FinalizedRegistrationRequest,
  FinishLoginParams,
  GetCodesParams,
  LogoutParams,
  MinistryUpdateRequest,
  RefreshParams,
  StartLoginParams,
  StartRegistrationParams,
  TypeUpdateRequest
} from './model';

import { axiosInstance } from '../services/common/axios-instance';
type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const updateEntries = (
    entryInputRequest: EntryInputRequest,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseVoid>(
      {url: `/api/entry/update_entries`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: entryInputRequest, signal
    },
      options);
    }
  


export const getUpdateEntriesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEntries>>, TError,{data: EntryInputRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateEntries>>, TError,{data: EntryInputRequest}, TContext> => {

const mutationKey = ['updateEntries'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateEntries>>, {data: EntryInputRequest}> = (props) => {
          const {data} = props ?? {};

          return  updateEntries(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateEntriesMutationResult = NonNullable<Awaited<ReturnType<typeof updateEntries>>>
    export type UpdateEntriesMutationBody = EntryInputRequest
    export type UpdateEntriesMutationError = unknown

    export const useUpdateEntries = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateEntries>>, TError,{data: EntryInputRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateEntries>>,
        TError,
        {data: EntryInputRequest},
        TContext
      > => {
      return useMutation(getUpdateEntriesMutationOptions(options), queryClient);
    }
    
export const updateTypes = (
    typeUpdateRequest: TypeUpdateRequest[],
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseVoid>(
      {url: `/api/common/update_types`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: typeUpdateRequest, signal
    },
      options);
    }
  


export const getUpdateTypesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTypes>>, TError,{data: TypeUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateTypes>>, TError,{data: TypeUpdateRequest[]}, TContext> => {

const mutationKey = ['updateTypes'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateTypes>>, {data: TypeUpdateRequest[]}> = (props) => {
          const {data} = props ?? {};

          return  updateTypes(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateTypesMutationResult = NonNullable<Awaited<ReturnType<typeof updateTypes>>>
    export type UpdateTypesMutationBody = TypeUpdateRequest[]
    export type UpdateTypesMutationError = unknown

    export const useUpdateTypes = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateTypes>>, TError,{data: TypeUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateTypes>>,
        TError,
        {data: TypeUpdateRequest[]},
        TContext
      > => {
      return useMutation(getUpdateTypesMutationOptions(options), queryClient);
    }
    
export const updateCodes = (
    codeUpdateRequest: CodeUpdateRequest[],
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseVoid>(
      {url: `/api/common/update_codes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: codeUpdateRequest, signal
    },
      options);
    }
  


export const getUpdateCodesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCodes>>, TError,{data: CodeUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateCodes>>, TError,{data: CodeUpdateRequest[]}, TContext> => {

const mutationKey = ['updateCodes'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateCodes>>, {data: CodeUpdateRequest[]}> = (props) => {
          const {data} = props ?? {};

          return  updateCodes(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateCodesMutationResult = NonNullable<Awaited<ReturnType<typeof updateCodes>>>
    export type UpdateCodesMutationBody = CodeUpdateRequest[]
    export type UpdateCodesMutationError = unknown

    export const useUpdateCodes = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateCodes>>, TError,{data: CodeUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateCodes>>,
        TError,
        {data: CodeUpdateRequest[]},
        TContext
      > => {
      return useMutation(getUpdateCodesMutationOptions(options), queryClient);
    }
    
export const startRegistration = (
    params: StartRegistrationParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseStartRegistrationResponse>(
      {url: `/api/auth/register/options`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getStartRegistrationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRegistration>>, TError,{params: StartRegistrationParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startRegistration>>, TError,{params: StartRegistrationParams}, TContext> => {

const mutationKey = ['startRegistration'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startRegistration>>, {params: StartRegistrationParams}> = (props) => {
          const {params} = props ?? {};

          return  startRegistration(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof startRegistration>>>
    
    export type StartRegistrationMutationError = unknown

    export const useStartRegistration = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRegistration>>, TError,{params: StartRegistrationParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startRegistration>>,
        TError,
        {params: StartRegistrationParams},
        TContext
      > => {
      return useMutation(getStartRegistrationMutationOptions(options), queryClient);
    }
    
export const finishRegistration = (
    finalizedRegistrationRequest: FinalizedRegistrationRequest,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/auth/register/finish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: finalizedRegistrationRequest, signal
    },
      options);
    }
  


export const getFinishRegistrationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishRegistration>>, TError,{data: FinalizedRegistrationRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof finishRegistration>>, TError,{data: FinalizedRegistrationRequest}, TContext> => {

const mutationKey = ['finishRegistration'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finishRegistration>>, {data: FinalizedRegistrationRequest}> = (props) => {
          const {data} = props ?? {};

          return  finishRegistration(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FinishRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof finishRegistration>>>
    export type FinishRegistrationMutationBody = FinalizedRegistrationRequest
    export type FinishRegistrationMutationError = unknown

    export const useFinishRegistration = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishRegistration>>, TError,{data: FinalizedRegistrationRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finishRegistration>>,
        TError,
        {data: FinalizedRegistrationRequest},
        TContext
      > => {
      return useMutation(getFinishRegistrationMutationOptions(options), queryClient);
    }
    
export const refresh = (
    params: RefreshParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseTokenResponse>(
      {url: `/api/auth/refresh`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getRefreshMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,{params: RefreshParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,{params: RefreshParams}, TContext> => {

const mutationKey = ['refresh'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof refresh>>, {params: RefreshParams}> = (props) => {
          const {params} = props ?? {};

          return  refresh(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type RefreshMutationResult = NonNullable<Awaited<ReturnType<typeof refresh>>>
    
    export type RefreshMutationError = unknown

    export const useRefresh = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof refresh>>, TError,{params: RefreshParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof refresh>>,
        TError,
        {params: RefreshParams},
        TContext
      > => {
      return useMutation(getRefreshMutationOptions(options), queryClient);
    }
    
export const logout = (
    params: LogoutParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseVoid>(
      {url: `/api/auth/logout`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getLogoutMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{params: LogoutParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{params: LogoutParams}, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, {params: LogoutParams}> = (props) => {
          const {params} = props ?? {};

          return  logout(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = unknown

    export const useLogout = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,{params: LogoutParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        {params: LogoutParams},
        TContext
      > => {
      return useMutation(getLogoutMutationOptions(options), queryClient);
    }
    
export const startLogin = (
    params: StartLoginParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseLoginResponse>(
      {url: `/api/auth/login/options`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getStartLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startLogin>>, TError,{params: StartLoginParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startLogin>>, TError,{params: StartLoginParams}, TContext> => {

const mutationKey = ['startLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startLogin>>, {params: StartLoginParams}> = (props) => {
          const {params} = props ?? {};

          return  startLogin(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartLoginMutationResult = NonNullable<Awaited<ReturnType<typeof startLogin>>>
    
    export type StartLoginMutationError = unknown

    export const useStartLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startLogin>>, TError,{params: StartLoginParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startLogin>>,
        TError,
        {params: StartLoginParams},
        TContext
      > => {
      return useMutation(getStartLoginMutationOptions(options), queryClient);
    }
    
export const finishLogin = (
    finishLoginBody: string,
    params: FinishLoginParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseTokenResponse>(
      {url: `/api/auth/login/finish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: finishLoginBody,
        params, signal
    },
      options);
    }
  


export const getFinishLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishLogin>>, TError,{data: string;params: FinishLoginParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof finishLogin>>, TError,{data: string;params: FinishLoginParams}, TContext> => {

const mutationKey = ['finishLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finishLogin>>, {data: string;params: FinishLoginParams}> = (props) => {
          const {data,params} = props ?? {};

          return  finishLogin(data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FinishLoginMutationResult = NonNullable<Awaited<ReturnType<typeof finishLogin>>>
    export type FinishLoginMutationBody = string
    export type FinishLoginMutationError = unknown

    export const useFinishLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishLogin>>, TError,{data: string;params: FinishLoginParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finishLogin>>,
        TError,
        {data: string;params: FinishLoginParams},
        TContext
      > => {
      return useMutation(getFinishLoginMutationOptions(options), queryClient);
    }
    
export const updateMinistries = (
    ministryUpdateRequest: MinistryUpdateRequest[],
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseVoid>(
      {url: `/api/account/update_ministries`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: ministryUpdateRequest, signal
    },
      options);
    }
  


export const getUpdateMinistriesMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMinistries>>, TError,{data: MinistryUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateMinistries>>, TError,{data: MinistryUpdateRequest[]}, TContext> => {

const mutationKey = ['updateMinistries'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateMinistries>>, {data: MinistryUpdateRequest[]}> = (props) => {
          const {data} = props ?? {};

          return  updateMinistries(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateMinistriesMutationResult = NonNullable<Awaited<ReturnType<typeof updateMinistries>>>
    export type UpdateMinistriesMutationBody = MinistryUpdateRequest[]
    export type UpdateMinistriesMutationError = unknown

    export const useUpdateMinistries = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateMinistries>>, TError,{data: MinistryUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateMinistries>>,
        TError,
        {data: MinistryUpdateRequest[]},
        TContext
      > => {
      return useMutation(getUpdateMinistriesMutationOptions(options), queryClient);
    }
    
export const updateBanks = (
    bankUpdateRequest: BankUpdateRequest[],
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseVoid>(
      {url: `/api/account/update_banks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: bankUpdateRequest, signal
    },
      options);
    }
  


export const getUpdateBanksMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBanks>>, TError,{data: BankUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateBanks>>, TError,{data: BankUpdateRequest[]}, TContext> => {

const mutationKey = ['updateBanks'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateBanks>>, {data: BankUpdateRequest[]}> = (props) => {
          const {data} = props ?? {};

          return  updateBanks(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateBanksMutationResult = NonNullable<Awaited<ReturnType<typeof updateBanks>>>
    export type UpdateBanksMutationBody = BankUpdateRequest[]
    export type UpdateBanksMutationError = unknown

    export const useUpdateBanks = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateBanks>>, TError,{data: BankUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateBanks>>,
        TError,
        {data: BankUpdateRequest[]},
        TContext
      > => {
      return useMutation(getUpdateBanksMutationOptions(options), queryClient);
    }
    
export const updateAccounts = (
    accountUpdateRequest: AccountUpdateRequest[],
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseVoid>(
      {url: `/api/account/update_accounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: accountUpdateRequest, signal
    },
      options);
    }
  


export const getUpdateAccountsMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAccounts>>, TError,{data: AccountUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateAccounts>>, TError,{data: AccountUpdateRequest[]}, TContext> => {

const mutationKey = ['updateAccounts'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateAccounts>>, {data: AccountUpdateRequest[]}> = (props) => {
          const {data} = props ?? {};

          return  updateAccounts(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateAccountsMutationResult = NonNullable<Awaited<ReturnType<typeof updateAccounts>>>
    export type UpdateAccountsMutationBody = AccountUpdateRequest[]
    export type UpdateAccountsMutationError = unknown

    export const useUpdateAccounts = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateAccounts>>, TError,{data: AccountUpdateRequest[]}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateAccounts>>,
        TError,
        {data: AccountUpdateRequest[]},
        TContext
      > => {
      return useMutation(getUpdateAccountsMutationOptions(options), queryClient);
    }
    
export const getTypes = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseListTypeResponse>(
      {url: `/api/common/get_types`, method: 'GET', signal
    },
      options);
    }
  



export const getGetTypesQueryKey = () => {
    return [
    `/api/common/get_types`
    ] as const;
    }

    
export const getGetTypesQueryOptions = <TData = Awaited<ReturnType<typeof getTypes>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTypes>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTypesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTypes>>> = ({ signal }) => getTypes(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTypes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTypesQueryResult = NonNullable<Awaited<ReturnType<typeof getTypes>>>
export type GetTypesQueryError = unknown


export function useGetTypes<TData = Awaited<ReturnType<typeof getTypes>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTypes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTypes>>,
          TError,
          Awaited<ReturnType<typeof getTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTypes<TData = Awaited<ReturnType<typeof getTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTypes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTypes>>,
          TError,
          Awaited<ReturnType<typeof getTypes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTypes<TData = Awaited<ReturnType<typeof getTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTypes>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetTypes<TData = Awaited<ReturnType<typeof getTypes>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTypes>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTypesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}


export const invalidateGetTypes = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetTypesQueryKey() }, options);

  return queryClient;
}



export const getCodes = (
    params?: GetCodesParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseListCodeResponse>(
      {url: `/api/common/get_codes`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getGetCodesQueryKey = (params?: GetCodesParams,) => {
    return [
    `/api/common/get_codes`, ...(params ? [params] : [])
    ] as const;
    }

    
export const getGetCodesQueryOptions = <TData = Awaited<ReturnType<typeof getCodes>>, TError = unknown>(params?: GetCodesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCodes>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCodesQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCodes>>> = ({ signal }) => getCodes(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCodes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCodesQueryResult = NonNullable<Awaited<ReturnType<typeof getCodes>>>
export type GetCodesQueryError = unknown


export function useGetCodes<TData = Awaited<ReturnType<typeof getCodes>>, TError = unknown>(
 params: undefined |  GetCodesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCodes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCodes>>,
          TError,
          Awaited<ReturnType<typeof getCodes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCodes<TData = Awaited<ReturnType<typeof getCodes>>, TError = unknown>(
 params?: GetCodesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCodes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCodes>>,
          TError,
          Awaited<ReturnType<typeof getCodes>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCodes<TData = Awaited<ReturnType<typeof getCodes>>, TError = unknown>(
 params?: GetCodesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCodes>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetCodes<TData = Awaited<ReturnType<typeof getCodes>>, TError = unknown>(
 params?: GetCodesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCodes>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCodesQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}


export const invalidateGetCodes = async (
 queryClient: QueryClient, params?: GetCodesParams, options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetCodesQueryKey(params) }, options);

  return queryClient;
}



export const getMinistries = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseListMinistryResponse>(
      {url: `/api/account/get_ministries`, method: 'GET', signal
    },
      options);
    }
  



export const getGetMinistriesQueryKey = () => {
    return [
    `/api/account/get_ministries`
    ] as const;
    }

    
export const getGetMinistriesQueryOptions = <TData = Awaited<ReturnType<typeof getMinistries>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinistries>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMinistriesQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMinistries>>> = ({ signal }) => getMinistries(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMinistries>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMinistriesQueryResult = NonNullable<Awaited<ReturnType<typeof getMinistries>>>
export type GetMinistriesQueryError = unknown


export function useGetMinistries<TData = Awaited<ReturnType<typeof getMinistries>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinistries>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMinistries>>,
          TError,
          Awaited<ReturnType<typeof getMinistries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMinistries<TData = Awaited<ReturnType<typeof getMinistries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinistries>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMinistries>>,
          TError,
          Awaited<ReturnType<typeof getMinistries>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMinistries<TData = Awaited<ReturnType<typeof getMinistries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinistries>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetMinistries<TData = Awaited<ReturnType<typeof getMinistries>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMinistries>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMinistriesQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}


export const invalidateGetMinistries = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetMinistriesQueryKey() }, options);

  return queryClient;
}



export const getBanks = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseListBankResponse>(
      {url: `/api/account/get_banks`, method: 'GET', signal
    },
      options);
    }
  



export const getGetBanksQueryKey = () => {
    return [
    `/api/account/get_banks`
    ] as const;
    }

    
export const getGetBanksQueryOptions = <TData = Awaited<ReturnType<typeof getBanks>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBanks>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBanksQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBanks>>> = ({ signal }) => getBanks(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBanks>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBanksQueryResult = NonNullable<Awaited<ReturnType<typeof getBanks>>>
export type GetBanksQueryError = unknown


export function useGetBanks<TData = Awaited<ReturnType<typeof getBanks>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBanks>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBanks>>,
          TError,
          Awaited<ReturnType<typeof getBanks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBanks<TData = Awaited<ReturnType<typeof getBanks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBanks>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBanks>>,
          TError,
          Awaited<ReturnType<typeof getBanks>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBanks<TData = Awaited<ReturnType<typeof getBanks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBanks>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetBanks<TData = Awaited<ReturnType<typeof getBanks>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBanks>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBanksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}


export const invalidateGetBanks = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetBanksQueryKey() }, options);

  return queryClient;
}



export const getAccounts = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseListAccountResponse>(
      {url: `/api/account/get_accounts`, method: 'GET', signal
    },
      options);
    }
  



export const getGetAccountsQueryKey = () => {
    return [
    `/api/account/get_accounts`
    ] as const;
    }

    
export const getGetAccountsQueryOptions = <TData = Awaited<ReturnType<typeof getAccounts>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccounts>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAccountsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAccounts>>> = ({ signal }) => getAccounts(requestOptions, signal);

      

      

   return  { queryKey, queryFn,   staleTime: Infinity, refetchOnWindowFocus: false,  ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAccounts>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAccountsQueryResult = NonNullable<Awaited<ReturnType<typeof getAccounts>>>
export type GetAccountsQueryError = unknown


export function useGetAccounts<TData = Awaited<ReturnType<typeof getAccounts>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccounts>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccounts>>,
          TError,
          Awaited<ReturnType<typeof getAccounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAccounts<TData = Awaited<ReturnType<typeof getAccounts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccounts>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAccounts>>,
          TError,
          Awaited<ReturnType<typeof getAccounts>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAccounts<TData = Awaited<ReturnType<typeof getAccounts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccounts>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useGetAccounts<TData = Awaited<ReturnType<typeof getAccounts>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAccounts>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAccountsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}


export const invalidateGetAccounts = async (
 queryClient: QueryClient,  options?: InvalidateOptions
  ): Promise<QueryClient> => {

  await queryClient.invalidateQueries({ queryKey: getGetAccountsQueryKey() }, options);

  return queryClient;
}
