/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ApiResponseAccountManagementResponse,
  ApiResponseLoginResponse,
  ApiResponseStartRegistrationResponse,
  ApiResponseString,
  FinalizedRegistrationRequest,
  FinishLoginParams,
  StartLoginParams,
  StartRegistrationParams
} from './model';

import { axiosInstance } from '../custom/config/axios-instance';


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const startRegistration = (
    params: StartRegistrationParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseStartRegistrationResponse>(
      {url: `/api/auth/register/options`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getStartRegistrationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRegistration>>, TError,{params: StartRegistrationParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startRegistration>>, TError,{params: StartRegistrationParams}, TContext> => {

const mutationKey = ['startRegistration'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startRegistration>>, {params: StartRegistrationParams}> = (props) => {
          const {params} = props ?? {};

          return  startRegistration(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof startRegistration>>>
    
    export type StartRegistrationMutationError = unknown

    export const useStartRegistration = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRegistration>>, TError,{params: StartRegistrationParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startRegistration>>,
        TError,
        {params: StartRegistrationParams},
        TContext
      > => {
      return useMutation(getStartRegistrationMutationOptions(options), queryClient);
    }
    
export const finishRegistration = (
    finalizedRegistrationRequest: FinalizedRegistrationRequest,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<void>(
      {url: `/api/auth/register/finish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: finalizedRegistrationRequest, signal
    },
      options);
    }
  


export const getFinishRegistrationMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishRegistration>>, TError,{data: FinalizedRegistrationRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof finishRegistration>>, TError,{data: FinalizedRegistrationRequest}, TContext> => {

const mutationKey = ['finishRegistration'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finishRegistration>>, {data: FinalizedRegistrationRequest}> = (props) => {
          const {data} = props ?? {};

          return  finishRegistration(data,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FinishRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof finishRegistration>>>
    export type FinishRegistrationMutationBody = FinalizedRegistrationRequest
    export type FinishRegistrationMutationError = unknown

    export const useFinishRegistration = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishRegistration>>, TError,{data: FinalizedRegistrationRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finishRegistration>>,
        TError,
        {data: FinalizedRegistrationRequest},
        TContext
      > => {
      return useMutation(getFinishRegistrationMutationOptions(options), queryClient);
    }
    
export const startLogin = (
    params: StartLoginParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseLoginResponse>(
      {url: `/api/auth/login/options`, method: 'POST',
        params, signal
    },
      options);
    }
  


export const getStartLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startLogin>>, TError,{params: StartLoginParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof startLogin>>, TError,{params: StartLoginParams}, TContext> => {

const mutationKey = ['startLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startLogin>>, {params: StartLoginParams}> = (props) => {
          const {params} = props ?? {};

          return  startLogin(params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartLoginMutationResult = NonNullable<Awaited<ReturnType<typeof startLogin>>>
    
    export type StartLoginMutationError = unknown

    export const useStartLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startLogin>>, TError,{params: StartLoginParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startLogin>>,
        TError,
        {params: StartLoginParams},
        TContext
      > => {
      return useMutation(getStartLoginMutationOptions(options), queryClient);
    }
    
export const finishLogin = (
    finishLoginBody: string,
    params: FinishLoginParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseString>(
      {url: `/api/auth/login/finish`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: finishLoginBody,
        params, signal
    },
      options);
    }
  


export const getFinishLoginMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishLogin>>, TError,{data: string;params: FinishLoginParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof finishLogin>>, TError,{data: string;params: FinishLoginParams}, TContext> => {

const mutationKey = ['finishLogin'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finishLogin>>, {data: string;params: FinishLoginParams}> = (props) => {
          const {data,params} = props ?? {};

          return  finishLogin(data,params,requestOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FinishLoginMutationResult = NonNullable<Awaited<ReturnType<typeof finishLogin>>>
    export type FinishLoginMutationBody = string
    export type FinishLoginMutationError = unknown

    export const useFinishLogin = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishLogin>>, TError,{data: string;params: FinishLoginParams}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finishLogin>>,
        TError,
        {data: string;params: FinishLoginParams},
        TContext
      > => {
      return useMutation(getFinishLoginMutationOptions(options), queryClient);
    }
    
export const initAccountManagement = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<ApiResponseAccountManagementResponse>(
      {url: `/api/admin/account/init`, method: 'GET', signal
    },
      options);
    }
  



export const getInitAccountManagementQueryKey = () => {
    return [
    `/api/admin/account/init`
    ] as const;
    }

    
export const getInitAccountManagementQueryOptions = <TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInitAccountManagementQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof initAccountManagement>>> = ({ signal }) => initAccountManagement(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InitAccountManagementQueryResult = NonNullable<Awaited<ReturnType<typeof initAccountManagement>>>
export type InitAccountManagementQueryError = unknown


export function useInitAccountManagement<TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof initAccountManagement>>,
          TError,
          Awaited<ReturnType<typeof initAccountManagement>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInitAccountManagement<TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof initAccountManagement>>,
          TError,
          Awaited<ReturnType<typeof initAccountManagement>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInitAccountManagement<TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInitAccountManagement<TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInitAccountManagementQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}





