/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import * as axios from 'axios';
import type {
  AxiosError,
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  ApiResponseAccountManagementResponse,
  FinishLoginParams,
  FinishRegistrationParams,
  StartLoginParams,
  StartRegistrationParams
} from './model';

export const startRegistration = (
    params: StartRegistrationParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    
    
    return axios.default.post(
      `/api/auth/register/options`,undefined,{
        responseType: 'blob',
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getStartRegistrationMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRegistration>>, TError,{params: StartRegistrationParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof startRegistration>>, TError,{params: StartRegistrationParams}, TContext> => {

const mutationKey = ['startRegistration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startRegistration>>, {params: StartRegistrationParams}> = (props) => {
          const {params} = props ?? {};

          return  startRegistration(params,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof startRegistration>>>
    
    export type StartRegistrationMutationError = AxiosError<unknown>

    export const useStartRegistration = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startRegistration>>, TError,{params: StartRegistrationParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startRegistration>>,
        TError,
        {params: StartRegistrationParams},
        TContext
      > => {
      return useMutation(getStartRegistrationMutationOptions(options), queryClient);
    }
    
export const finishRegistration = (
    finishRegistrationBody: string,
    params: FinishRegistrationParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<void>> => {
    
    
    return axios.default.post(
      `/api/auth/register/finish`,
      finishRegistrationBody,{
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getFinishRegistrationMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishRegistration>>, TError,{data: string;params: FinishRegistrationParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof finishRegistration>>, TError,{data: string;params: FinishRegistrationParams}, TContext> => {

const mutationKey = ['finishRegistration'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finishRegistration>>, {data: string;params: FinishRegistrationParams}> = (props) => {
          const {data,params} = props ?? {};

          return  finishRegistration(data,params,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FinishRegistrationMutationResult = NonNullable<Awaited<ReturnType<typeof finishRegistration>>>
    export type FinishRegistrationMutationBody = string
    export type FinishRegistrationMutationError = AxiosError<unknown>

    export const useFinishRegistration = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishRegistration>>, TError,{data: string;params: FinishRegistrationParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finishRegistration>>,
        TError,
        {data: string;params: FinishRegistrationParams},
        TContext
      > => {
      return useMutation(getFinishRegistrationMutationOptions(options), queryClient);
    }
    
export const startLogin = (
    params: StartLoginParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    
    
    return axios.default.post(
      `/api/auth/login/options`,undefined,{
        responseType: 'blob',
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getStartLoginMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startLogin>>, TError,{params: StartLoginParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof startLogin>>, TError,{params: StartLoginParams}, TContext> => {

const mutationKey = ['startLogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof startLogin>>, {params: StartLoginParams}> = (props) => {
          const {params} = props ?? {};

          return  startLogin(params,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type StartLoginMutationResult = NonNullable<Awaited<ReturnType<typeof startLogin>>>
    
    export type StartLoginMutationError = AxiosError<unknown>

    export const useStartLogin = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof startLogin>>, TError,{params: StartLoginParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof startLogin>>,
        TError,
        {params: StartLoginParams},
        TContext
      > => {
      return useMutation(getStartLoginMutationOptions(options), queryClient);
    }
    
export const finishLogin = (
    finishLoginBody: string,
    params: FinishLoginParams, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Blob>> => {
    
    
    return axios.default.post(
      `/api/auth/login/finish`,
      finishLoginBody,{
        responseType: 'blob',
    ...options,
        params: {...params, ...options?.params},}
    );
  }



export const getFinishLoginMutationOptions = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishLogin>>, TError,{data: string;params: FinishLoginParams}, TContext>, axios?: AxiosRequestConfig}
): UseMutationOptions<Awaited<ReturnType<typeof finishLogin>>, TError,{data: string;params: FinishLoginParams}, TContext> => {

const mutationKey = ['finishLogin'];
const {mutation: mutationOptions, axios: axiosOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, axios: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof finishLogin>>, {data: string;params: FinishLoginParams}> = (props) => {
          const {data,params} = props ?? {};

          return  finishLogin(data,params,axiosOptions)
        }



        


  return  { mutationFn, ...mutationOptions }}

    export type FinishLoginMutationResult = NonNullable<Awaited<ReturnType<typeof finishLogin>>>
    export type FinishLoginMutationBody = string
    export type FinishLoginMutationError = AxiosError<unknown>

    export const useFinishLogin = <TError = AxiosError<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof finishLogin>>, TError,{data: string;params: FinishLoginParams}, TContext>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof finishLogin>>,
        TError,
        {data: string;params: FinishLoginParams},
        TContext
      > => {
      return useMutation(getFinishLoginMutationOptions(options), queryClient);
    }
    
export const initAccountManagement = (
     options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ApiResponseAccountManagementResponse>> => {
    
    
    return axios.default.get(
      `/api/admin/account/init`,options
    );
  }




export const getInitAccountManagementQueryKey = () => {
    return [
    `/api/admin/account/init`
    ] as const;
    }

    
export const getInitAccountManagementQueryOptions = <TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = AxiosError<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>>, axios?: AxiosRequestConfig}
) => {

const {query: queryOptions, axios: axiosOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getInitAccountManagementQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof initAccountManagement>>> = ({ signal }) => initAccountManagement({ signal, ...axiosOptions });

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type InitAccountManagementQueryResult = NonNullable<Awaited<ReturnType<typeof initAccountManagement>>>
export type InitAccountManagementQueryError = AxiosError<unknown>


export function useInitAccountManagement<TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = AxiosError<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof initAccountManagement>>,
          TError,
          Awaited<ReturnType<typeof initAccountManagement>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInitAccountManagement<TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof initAccountManagement>>,
          TError,
          Awaited<ReturnType<typeof initAccountManagement>>
        > , 'initialData'
      >, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useInitAccountManagement<TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useInitAccountManagement<TData = Awaited<ReturnType<typeof initAccountManagement>>, TError = AxiosError<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof initAccountManagement>>, TError, TData>>, axios?: AxiosRequestConfig}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getInitAccountManagementQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  return { ...query, queryKey: queryOptions.queryKey };
}
