import fs from 'node:fs';
import path from 'node:path';

const MODELS_DIR = './src/api/model';
const OUTPUT_DIR = './src/api/zod';
const COMMON_API_SCHEMA_PATH = '../common/api'; // Relative to OUTPUT_DIR if needed, but we'll use absolute-ish imports

if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

const files = fs.readdirSync(MODELS_DIR).filter(f => f.endsWith('.ts') && f !== 'index.ts');

function camelCase(str) {
  return str.charAt(0).toLowerCase() + str.slice(1);
}

function toZodSchemaName(typeName) {
  return camelCase(typeName) + 'Schema';
}

const PRIMITIVE_TYPES = ['string', 'number', 'boolean', 'any', 'unknown'];

function mapType(type, isOptional) {
  const typeParts = type.split('|').map((t) => t.trim());
  const includesNull = typeParts.includes('null');
  const pureType = typeParts.filter((t) => t !== 'null' && t !== 'undefined').join('|');

  let zodType;
  if (pureType === 'string') zodType = 'z.string()';
  else if (pureType === 'number') zodType = 'z.number()';
  else if (pureType === 'boolean') zodType = 'z.boolean()';
  else if (pureType === 'any') zodType = 'z.any()';
  else if (pureType === 'unknown') zodType = 'z.unknown()';
  else if (pureType.endsWith('[]')) {
    const baseType = pureType.slice(0, -2);
    if (PRIMITIVE_TYPES.includes(baseType)) {
      zodType = `z.array(${mapType(baseType, false)})`;
    } else {
      zodType = `z.array(${toZodSchemaName(baseType)})`;
    }
  } else {
    zodType = toZodSchemaName(pureType);
  }

  if(includesNull) {
    zodType += '.nullable()';
  }

  if (isOptional) {
    zodType += '.optional()';
  }
  
  return zodType;
}

files.forEach(file => {
  if (file.startsWith('apiResponse')) return; // Skip the wrappers generated by Orval

  const content = fs.readFileSync(path.join(MODELS_DIR, file), 'utf8');
  const fileNameNoExt = file.replace('.ts', '');
  
  // Extract imports
  const importLines = content.match(/import type \{ ([\w, ]+) \} from '\.\/([\w-]+)';/g) || [];
  const zodImports = importLines.map(line => {
    const [_, types, from] = line.match(/import type \{ ([\w, ]+) \} from '\.\/([\w-]+)';/);
    if (from.startsWith('apiResponse')) return ''; // Skip
    return `import { ${types.split(',').map(t => toZodSchemaName(t.trim())).join(', ')} } from './${from}.zod';`;
  }).filter(Boolean);

  // Extract interface or type
  const interfaceMatch = content.match(/export interface (\w+) \{([\s\S]*?)\}/);
  const typeMatch = content.match(/export type (\w+) = ([\s\S]*?);/);

  let outputContent = `import { z } from 'zod';\n`;
  
  if (interfaceMatch) {
    const [_, interfaceName, fieldsBlock] = interfaceMatch;
    const schemaName = toZodSchemaName(interfaceName);
    
    // Add imports
    if (zodImports.length > 0) {
      outputContent += zodImports.join('\n') + '\n';
    }
    
    // Handle Response suffix
    const isResponse = interfaceName.endsWith('Response');
    if (isResponse) {
      outputContent += `import { createApiResponseSchema } from '../../schemas/common/api';\n`;
    }

    outputContent += `\nexport const ${schemaName} = z.object({\n`;
    
    const fieldLines = fieldsBlock.trim().split('\n');
    fieldLines.forEach(line => {
      const match = line.match(/^\s*(\w+)(\??): (.+);/);
      if (match) {
        const [__, fieldName, optional, type] = match;
        outputContent += `  ${fieldName}: ${mapType(type, !!optional)},\n`;
      }
    });
    
    outputContent += `});\n\n`;

    if (isResponse) {
      const dataSchemaName = camelCase(interfaceName.replace('Response', 'DataSchema'));
      const initSchemaName = `init${interfaceName}Schema`;
      
      outputContent += `export const ${dataSchemaName} = ${schemaName};\n\n`;
      outputContent += `export const ${initSchemaName} =\n  createApiResponseSchema(${dataSchemaName});\n\n`;
      
      outputContent += `export type ${interfaceName.replace('Response', 'Data')} = z.infer<\n  typeof ${dataSchemaName}\n>;\n\n`;
      outputContent += `export type Init${interfaceName} = z.infer<\n  typeof ${initSchemaName}\n>;\n`;
    } else {
      outputContent += `export type ${interfaceName} = z.infer<typeof ${schemaName}>;\n`;
    }

  } else if (typeMatch) {
    const [_, typeName, typeValue] = typeMatch;
    const schemaName = toZodSchemaName(typeName);
    
    // Check if it's an enum-like type
    if (content.includes(`export const ${typeName} = {`)) {
        outputContent += `import { ${typeName} as ${typeName}Model } from '../model/${fileNameNoExt}';\n`;
        outputContent += `\nexport const ${schemaName} = z.nativeEnum(${typeName}Model);\n`;
    } else {
        // Handle simple types like appId: string
        if (typeValue.trim() === 'string') {
            outputContent += `\nexport const ${schemaName} = z.string();\n`;
        } else if (typeValue.trim() === 'number') {
            outputContent += `\nexport const ${schemaName} = z.number();\n`;
        } else {
            outputContent += `\nexport const ${schemaName} = z.any();\n`;
        }
    }
    outputContent += `export type ${typeName} = z.infer<typeof ${schemaName}>;\n`;
  }

  fs.writeFileSync(path.join(OUTPUT_DIR, `${fileNameNoExt}.zod.ts`), outputContent);
});


console.log('Zod schemas generated in src/api/zod/');
