/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */

export interface AccountUpdateRequest {
  id?: number;
  bankId?: number;
  accountType?: string;
  name?: string;
  owner?: string;
  currencyType?: string;
  accountNumber?: string;
  description?: string;
  requestedBy?: string;
  toDelete?: boolean;
}
