/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */
import type { ApiError } from './apiError';
import type { CodeResponse } from './codeResponse';

export interface ApiResponseListCodeResponse {
  success?: boolean;
  apiError?: ApiError;
  data?: CodeResponse[];
}
