/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */
import type { AuthenticatorSelectionCriteriaAuthenticatorAttachment } from './authenticatorSelectionCriteriaAuthenticatorAttachment';
import type { AuthenticatorSelectionCriteriaResidentKey } from './authenticatorSelectionCriteriaResidentKey';
import type { AuthenticatorSelectionCriteriaUserVerification } from './authenticatorSelectionCriteriaUserVerification';

export interface AuthenticatorSelectionCriteria {
  authenticatorAttachment?: AuthenticatorSelectionCriteriaAuthenticatorAttachment;
  requireResidentKey?: boolean;
  residentKey?: AuthenticatorSelectionCriteriaResidentKey;
  userVerification?: AuthenticatorSelectionCriteriaUserVerification;
}
