/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */
import type { EntryUpdateRequest } from './entryUpdateRequest';
import type { SourceUpdateRequest } from './sourceUpdateRequest';
import type { TagUpdateRequest } from './tagUpdateRequest';

export interface EntryInputRequest {
  entryUpdateRequests: EntryUpdateRequest[];
  sourceUpdateRequests?: SourceUpdateRequest[];
  tagUpdateRequests?: TagUpdateRequest[];
}
