/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */

export interface EntryUpdateRequest {
  id?: number;
  accountId: number;
  date: string;
  amount: number;
  memo?: string;
  connection: string;
  ministryId?: number;
  tagName?: string;
  /** @pattern inc|exp */
  entryType: string;
  toDelete?: boolean;
}
