/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */
import type { PublicKeyCredentialParametersAlg } from './publicKeyCredentialParametersAlg';
import type { PublicKeyCredentialParametersType } from './publicKeyCredentialParametersType';

export interface PublicKeyCredentialParameters {
  alg?: PublicKeyCredentialParametersAlg;
  type?: PublicKeyCredentialParametersType;
}
