/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */

export type PublicKeyCredentialParametersAlg = typeof PublicKeyCredentialParametersAlg[keyof typeof PublicKeyCredentialParametersAlg];


export const PublicKeyCredentialParametersAlg = {
  NUMBER_MINUS_8: '-8',
  NUMBER_MINUS_7: '-7',
  NUMBER_MINUS_35: '-35',
  NUMBER_MINUS_36: '-36',
  NUMBER_MINUS_257: '-257',
  NUMBER_MINUS_258: '-258',
  NUMBER_MINUS_259: '-259',
  NUMBER_MINUS_65535: '-65535',
} as const;
