/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */

export type PublicKeyCredentialCreationOptionsAttestation = typeof PublicKeyCredentialCreationOptionsAttestation[keyof typeof PublicKeyCredentialCreationOptionsAttestation];


export const PublicKeyCredentialCreationOptionsAttestation = {
  none: 'none',
  indirect: 'indirect',
  direct: 'direct',
  enterprise: 'enterprise',
} as const;
