/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */
import type { AuthenticatorSelectionCriteria } from './authenticatorSelectionCriteria';
import type { PublicKeyCredentialCreationOptionsAttestation } from './publicKeyCredentialCreationOptionsAttestation';
import type { PublicKeyCredentialDescriptor } from './publicKeyCredentialDescriptor';
import type { PublicKeyCredentialParameters } from './publicKeyCredentialParameters';
import type { RegistrationExtensionInputs } from './registrationExtensionInputs';
import type { RelyingPartyIdentity } from './relyingPartyIdentity';
import type { UserIdentity } from './userIdentity';

export interface PublicKeyCredentialCreationOptions {
  rp?: RelyingPartyIdentity;
  user?: UserIdentity;
  challenge?: string;
  pubKeyCredParams?: PublicKeyCredentialParameters[];
  timeout?: number;
  excludeCredentials?: PublicKeyCredentialDescriptor[];
  authenticatorSelection?: AuthenticatorSelectionCriteria;
  attestation?: PublicKeyCredentialCreationOptionsAttestation;
  extensions?: RegistrationExtensionInputs;
}
