/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Project HOME
 * 백엔드 멀티 모듈 API 명세서
 * OpenAPI spec version: 1.0
 */
import type { AppId } from './appId';
import type { LargeBlobRegistrationInput } from './largeBlobRegistrationInput';

export interface RegistrationExtensionInputs {
  appidExclude?: AppId;
  credProps?: boolean;
  largeBlob?: LargeBlobRegistrationInput;
  uvm?: boolean;
}
