/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routers/__root'
import { Route as LoginRouteImport } from './routers/login'
import { Route as HomeRouteImport } from './routers/home'
import { Route as IndexRouteImport } from './routers/index'
import { Route as ManagementMinistryRouteImport } from './routers/management/ministry'
import { Route as ManagementCodeRouteImport } from './routers/management/code'
import { Route as ManagementBankRouteImport } from './routers/management/bank'
import { Route as ManagementAccountRouteImport } from './routers/management/account'
import { Route as FinanceInsertRouteImport } from './routers/finance/insert'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementMinistryRoute = ManagementMinistryRouteImport.update({
  id: '/management/ministry',
  path: '/management/ministry',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementCodeRoute = ManagementCodeRouteImport.update({
  id: '/management/code',
  path: '/management/code',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementBankRoute = ManagementBankRouteImport.update({
  id: '/management/bank',
  path: '/management/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const ManagementAccountRoute = ManagementAccountRouteImport.update({
  id: '/management/account',
  path: '/management/account',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceInsertRoute = FinanceInsertRouteImport.update({
  id: '/finance/insert',
  path: '/finance/insert',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/finance/insert': typeof FinanceInsertRoute
  '/management/account': typeof ManagementAccountRoute
  '/management/bank': typeof ManagementBankRoute
  '/management/code': typeof ManagementCodeRoute
  '/management/ministry': typeof ManagementMinistryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/finance/insert': typeof FinanceInsertRoute
  '/management/account': typeof ManagementAccountRoute
  '/management/bank': typeof ManagementBankRoute
  '/management/code': typeof ManagementCodeRoute
  '/management/ministry': typeof ManagementMinistryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/finance/insert': typeof FinanceInsertRoute
  '/management/account': typeof ManagementAccountRoute
  '/management/bank': typeof ManagementBankRoute
  '/management/code': typeof ManagementCodeRoute
  '/management/ministry': typeof ManagementMinistryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/home'
    | '/login'
    | '/finance/insert'
    | '/management/account'
    | '/management/bank'
    | '/management/code'
    | '/management/ministry'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/home'
    | '/login'
    | '/finance/insert'
    | '/management/account'
    | '/management/bank'
    | '/management/code'
    | '/management/ministry'
  id:
    | '__root__'
    | '/'
    | '/home'
    | '/login'
    | '/finance/insert'
    | '/management/account'
    | '/management/bank'
    | '/management/code'
    | '/management/ministry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  FinanceInsertRoute: typeof FinanceInsertRoute
  ManagementAccountRoute: typeof ManagementAccountRoute
  ManagementBankRoute: typeof ManagementBankRoute
  ManagementCodeRoute: typeof ManagementCodeRoute
  ManagementMinistryRoute: typeof ManagementMinistryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/ministry': {
      id: '/management/ministry'
      path: '/management/ministry'
      fullPath: '/management/ministry'
      preLoaderRoute: typeof ManagementMinistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/code': {
      id: '/management/code'
      path: '/management/code'
      fullPath: '/management/code'
      preLoaderRoute: typeof ManagementCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/bank': {
      id: '/management/bank'
      path: '/management/bank'
      fullPath: '/management/bank'
      preLoaderRoute: typeof ManagementBankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/management/account': {
      id: '/management/account'
      path: '/management/account'
      fullPath: '/management/account'
      preLoaderRoute: typeof ManagementAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance/insert': {
      id: '/finance/insert'
      path: '/finance/insert'
      fullPath: '/finance/insert'
      preLoaderRoute: typeof FinanceInsertRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  FinanceInsertRoute: FinanceInsertRoute,
  ManagementAccountRoute: ManagementAccountRoute,
  ManagementBankRoute: ManagementBankRoute,
  ManagementCodeRoute: ManagementCodeRoute,
  ManagementMinistryRoute: ManagementMinistryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
