/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routers/__root'
import { Route as MinistryRouteImport } from './routers/management/ministry'
import { Route as LoginRouteImport } from './routers/login'
import { Route as HomeRouteImport } from './routers/home'
import { Route as CodeRouteImport } from './routers/management/code'
import { Route as BankRouteImport } from './routers/management/bank'
import { Route as AccountRouteImport } from './routers/management/account'
import { Route as IndexRouteImport } from './routers/index'

const MinistryRoute = MinistryRouteImport.update({
  id: '/ministry',
  path: '/ministry',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeRoute = CodeRouteImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => rootRouteImport,
} as any)
const BankRoute = BankRouteImport.update({
  id: '/bank',
  path: '/bank',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bank': typeof BankRoute
  '/code': typeof CodeRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/ministry': typeof MinistryRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bank': typeof BankRoute
  '/code': typeof CodeRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/ministry': typeof MinistryRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/bank': typeof BankRoute
  '/code': typeof CodeRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/ministry': typeof MinistryRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/bank'
    | '/code'
    | '/home'
    | '/login'
    | '/ministry'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/bank' | '/code' | '/home' | '/login' | '/ministry'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/bank'
    | '/code'
    | '/home'
    | '/login'
    | '/ministry'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  BankRoute: typeof BankRoute
  CodeRoute: typeof CodeRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MinistryRoute: typeof MinistryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/ministry': {
      id: '/ministry'
      path: '/ministry'
      fullPath: '/ministry'
      preLoaderRoute: typeof MinistryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code': {
      id: '/code'
      path: '/code'
      fullPath: '/code'
      preLoaderRoute: typeof CodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof BankRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  BankRoute: BankRoute,
  CodeRoute: CodeRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MinistryRoute: MinistryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
