/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as authLoginRouteImport } from './routes/auth/login'
import { Route as mainMainHomeRouteImport } from './routes/main/mainHome'
import { Route as managementBankManagementRouteImport } from './routes/management/bankManagement'
import { Route as managementAccountManagementRouteImport } from './routes/management/accountManagement'
import { Route as authRegisterRouteImport } from './routes/auth/register'

const authLoginRoute = authLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const mainMainHomeRoute = mainMainHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const managementBankManagementRoute =
  managementBankManagementRouteImport.update({
    id: '/bank',
    path: '/bank',
    getParentRoute: () => rootRouteImport,
  } as any)
const managementAccountManagementRoute =
  managementAccountManagementRouteImport.update({
    id: '/account',
    path: '/account',
    getParentRoute: () => rootRouteImport,
  } as any)
const authRegisterRoute = authRegisterRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof authRegisterRoute
  '/account': typeof managementAccountManagementRoute
  '/bank': typeof managementBankManagementRoute
  '/home': typeof mainMainHomeRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesByTo {
  '/': typeof authRegisterRoute
  '/account': typeof managementAccountManagementRoute
  '/bank': typeof managementBankManagementRoute
  '/home': typeof mainMainHomeRoute
  '/login': typeof authLoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof authRegisterRoute
  '/account': typeof managementAccountManagementRoute
  '/bank': typeof managementBankManagementRoute
  '/home': typeof mainMainHomeRoute
  '/login': typeof authLoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/account' | '/bank' | '/home' | '/login'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/account' | '/bank' | '/home' | '/login'
  id: '__root__' | '/' | '/account' | '/bank' | '/home' | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  authRegisterRoute: typeof authRegisterRoute
  managementAccountManagementRoute: typeof managementAccountManagementRoute
  managementBankManagementRoute: typeof managementBankManagementRoute
  mainMainHomeRoute: typeof mainMainHomeRoute
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof mainMainHomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bank': {
      id: '/bank'
      path: '/bank'
      fullPath: '/bank'
      preLoaderRoute: typeof managementBankManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof managementAccountManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  authRegisterRoute: authRegisterRoute,
  managementAccountManagementRoute: managementAccountManagementRoute,
  managementBankManagementRoute: managementBankManagementRoute,
  mainMainHomeRoute: mainMainHomeRoute,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
