import { z } from 'zod';
import { AuthenticatorSelectionCriteriaAuthenticatorAttachment as AuthenticatorSelectionCriteriaAuthenticatorAttachmentModel } from '../model/authenticatorSelectionCriteriaAuthenticatorAttachment';

export const authenticatorSelectionCriteriaAuthenticatorAttachmentSchema = z.nativeEnum(AuthenticatorSelectionCriteriaAuthenticatorAttachmentModel);
export type AuthenticatorSelectionCriteriaAuthenticatorAttachment = z.infer<typeof authenticatorSelectionCriteriaAuthenticatorAttachmentSchema>;
